remote_theme: chesterhow/tale

# Site settings
title:          Applied Exploration
description:    "Exploring Advanced Computation"
url:            "https://applied-exploration.github.io/"

# Google Analytics
google_analytics: UA-198024164-1

# Author
author:
  name:         Mark Szulyovszky, Daniel Szemerey
  url:          https://applied-exploration.github.io/
  email:        _

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-remote-theme
  - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]







